# Generated by Django 3.1.2 on 2020-11-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=200)),
                ('access_type', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('total_occupancy', models.IntegerField(default=0)),
            ],
        ),
    ]
